interface=wlan0
driver=nl80211
ssid=TestCorp
channel=6
hw_mode=g
auth_algs=3
wpa=2
wpa_key_mgmt=WPA-EAP
wpa_pairwise=CCMP
rsn_pairwise=CCMP
ieee8021x=1
eap_server=1
eap_user_file=/home/atlantis/ordner/hostapd-wpe.eap_user
ca_cert=/home/atlantis/ordner/certs/ca.pem
server_cert=/home/atlantis/ordner/certs/server.pem
private_key=/home/atlantis/ordner/certs/server.key
private_key_passwd=whatever
wpe_logfile=/home/atlantis/ordner/wpe.log
logger_stdout=-1
logger_stdout_level=2
